AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  llm-search backend SAM template
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Environment:
      Variables:
        BING_API_KEY: !Ref BING_API_KEY
        AZURE_AI_API_KEY: !Ref AZURE_AI_API_KEY
        AZURE_AI_BASE_URL: !Ref AZURE_AI_BASE_URL
        HYPERBOLIC_AI_API_KEY: !Ref HYPERBOLIC_AI_API_KEY
  Api:
    Cors:
      AllowOrigin: "'*'" # To be changed

Resources:
  ChromiumLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      Description: Chromium with Node.js integration for AWS Lambda
      ContentUri: chromium-layer/
      CompatibleRuntimes: 
        - &nodejsRuntime nodejs20.x
      CompatibleArchitectures:
        - &chromiumArch x86_64
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: *nodejsRuntime
      BuildArchitecture: *chromiumArch

  MainFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: main/
      Handler: app.lambdaHandler
      Runtime: *nodejsRuntime
      Architectures: 
        - *chromiumArch
      Layers: 
        - !Ref ChromiumLayer
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /search
            Method: get
      Timeout: 30
      MemorySize: 4096
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
          - app.ts
        External:
          - "@sparticuz/chromium"
